# Generated by Django 2.2.17 on 2022-01-21 14:22

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.AddField(
            model_name='answer',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='poll',
            name='dt_close',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 14, 22, 35, 287098)),
        ),
    ]
